<?php
namespace Apps;

use Service\Apps;
use Service\HttpCode;

class Index extends Apps{

    public function authentication(){
        // TODO: Implement authentication() method.
    }

    public function done(): void{
        parent::done(); // TODO: Change the autogenerated stub
    }

    //GET
    public function execute(){
        return $this->packagingHttpResponse(HttpCode::API_CODE_OK, '', array(
            'code'      => HttpCode::API_CODE_OK,
            'message'   => '',
            'data'      => $this->params,
        ));
    }

    //POST
    public function post(){
        return $this->packagingHttpResponse(HttpCode::API_CODE_OK, '', array(
            'code'      => HttpCode::API_CODE_OK,
            'message'   => '',
            'data'      => $this->params,
        ));
    }
}