<?php
namespace Apps;

use Service\Apps;
use Service\HttpCode;

class Index extends Apps{

    public function authentication(){
        // TODO: Implement authentication() method.
    }

    public function done(): void{
        parent::done(); // TODO: Change the autogenerated stub
    }

    //GET
    public function execute(){
        return $this->packagingHttpResponse(HttpCode::API_CODE_OK, '', array(
            'code'      => HttpCode::API_CODE_OK,
            'message'   => '',
            'data'      => $this->params,
        ));
    }

    //POST
    public function post(){
        return $this->packagingHttpResponse(HttpCode::API_CODE_OK, '', array(
            'code'      => HttpCode::API_CODE_OK,
            'message'   => '',
            'data'      => [
                $this->params,
                $this->request->getBody(),
            ],
        ));
    }

    /**
     * 日志
     */
    public function log(){
        $this->logger->success("success");
        $this->logger->info("info");
        $this->logger->error("error");
        //自定义
        $this->logger->setContent('contents')
            ->setLevel('level')
            ->Logger();
    }

    //HTTP
    public function http(){
        $http   = new \Tools\Client\Http('IP', 80);
        //OR
        $http   = new \Tools\Client\Http('http://www.baidu.com/', 80);
        $ret    = $http->setMethod('GET')
            ->setPath('/')
            ->execute();

        $body   = $ret->getBody();
        $code   = $ret->getStatusCode();
        $error  = $ret->getErrCode();
    }

    //GET HEADER
    public function header(){
        $request    = $this->request;
        $headers    = $this->request->getHeader();
        $method     = $this->request->getMethod();
        $server     = $this->request->getServer();  //$_SERVER

    }
}